* Guia Linux
** TODO Comandos Importantes
   | Comando     | Descripcion                                       |
   | :------     | :----------                                       |
   | mhwd-kernel |                                                   |
   | ls -lt      | Lista los archivos ordenado por el último archivo |
   | ls -ltr     | r de reverse ?                                    |

   #+BEGIN_SRC sh
     mhwd-kernel -li
   #+END_SRC
   
*** Saber ultimo archivo descargado con el comando ls
   - https://www.tecmint.com/sort-ls-output-by-last-modified-date-and-time/
   - https://osxdaily.com/2017/02/02/ls-sort-by-date/

** Manipular el Historial de comandos
*** Comandos

    |---------------------+--------------------------------------------|
    | Comando             | Descripción                                |
    |---------------------+--------------------------------------------|
    | history -d unNumero | Elimina de historial ese número de comando |
    | history -c          | Limpia el historial                        |
    | history             | Imprime todo el historial                  |
    |                     |                                            |
    |---------------------+--------------------------------------------|
  
*** Ejemplos

    #+BEGIN_SRC shell
      # listamos el historial para navegar con los atajos de vim
      history | less
      history | more

      # listamos los últimos 10 comandos
      history | tail

      # listamos los últimos 30 comandos
      history 30

      # ejecutamos el comando del historial que tiene numerado con 5
      !5
      # ejecutamos el comando numero 101 del historial
      !101
    #+END_SRC
*** Referencias
    + [[https://www.tldp.org/LDP/GNU-Linux-Tools-Summary/html/x1712.htm][The command line history - (TLDP) The Linux Documentation Project]]
    + [[https://www.gnu.org/software/bash/manual/html_node/Bash-History-Builtins.html][Bash history builtins - gnu.org]]
    + [[https://opensource.com/article/18/6/history-command][How to use the history command -  opensource.com]]
    + [[https://mediatemple.net/community/products/dv/204404624/using-the-history-command][Using the history command - mediatemple.net]]
    + [[https://www.thegeekstuff.com/2008/08/15-examples-to-master-linux-command-line-history/][15 examples to master linux command line history - thegeekstuff.com]]

** TODO Comando awk
*** Ejemplos

    

*** Referencias
    + [[https://likegeeks.com/es/comando-awk/][Comando awk - likegeeks.com]]
** Utilidades Interesantes
*** Crear animaciones de captura de pantalla
   
    Algunos packages útiles: 
    + Con *xrectsel* se puede saber las posiciciones (x,y) el tamaño(width,height) de una parte de la pantalla
    + Con *byzanz-record* se captura pantalla en formato gif mediante lineas de comando
   
    Algunas páginas útiles:
    + Con *gfycat.com* se puede subir animaciones gif, permite verlos como si fuese un reproductor de video.

    #+NAME: Instalación y configuración
    #+BEGIN_SRC sh
      # para saber el tamaño de una ventana
      sudo pacman -S xrectsel
      # para capturar la pantalla y generar un gif
      sudo pacman -S byzanz-record

      # byzanz-record --delay=5 --duration=10 --width=400 --height=400 --x=0 --y=80 test1.gif
    #+END_SRC

    #+NAME: Script para capturar pantalla
    #+BEGIN_SRC sh
      # WINDOWS_SIZE=$(gdialog --title "Elegir ventana o tamanio" --yesno "Grabar una ventana o elegir tamanio?" 0 0)
      # if $WINDOWS_SIZE; then
      #     notify-send "elegiste si"
      # else
      #     notify-send "elegiste NO"
      # fi

      # Name
      TITLE=$(gdialog --title "TITLE?" --inputbox "Elija un titulo para la animación" 200 100 2>&1)

      # Time and date
      TIME=$(date +"%Y-%m-%d_%H%M%S")

      # Delay before starting
      DELAY=10

      # Standard screencast folder
      FOLDER="$HOME/Pictures"

      # Default recording duration
      DEFAULT_DURATION=10

      # Sound notification to let one know when recording is about to start (and ends)
      beep() {
          paplay /usr/share/sounds/freedesktop/stereo/message-new-instant.oga &
      }

      # Custom recording duration as set by user
      DURATION=$(gdialog --title "Duration?" --inputbox "Please enter the screencast duration in seconds" 200 100 2>&1)

      # Duration and output file
      if [ $DURATION -gt 0 ]; then
          D=$DURATION
      else
          D=$DEFAULT_DURATION
      fi

      # Window geometry
      # No funciona...
      # XWININFO=$(xwininfo)
      # read X <<(awk -F: '/Absolute upper-left X/{print $2}' <<< "$XWININFO")
      # read Y <<(awk -F: '/Absolute upper-left Y/{print $2}' <<< "$XWININFO")
      # read W <<(awk -F: '/Width/{print $2}' <<< "$XWININFO")
      # read H <<(awk -F: '/Height/{print $2}' <<< "$XWININFO")

      # estaba probando pero me falta entenderlo bien (?)
      # MYWINDOW = xrectsel
      #W = MYWINDOW | awk -F '{print $1}'

      # Notify the user of recording time and delay
      notify-send "GIFRecorder" "Recording duration set to $D seconds. Recording will start in $DELAY seconds."

      #Actual recording
      sleep $DELAY
      beep
      byzanz-record -c --verbose --delay=0 --duration=$D --x=$X --y=$Y --width=$W --height=$H "$FOLDER/GIFrecord_$TIME.gif"
      beep

      # Notify the user of end of recording.
      notify-send "GIFRecorder" "Screencast saved to $FOLDER/GIFrecord_$NAME_$TIME.gif"
    #+END_SRC

    #+RESULTS: Script para capturar pantalla
    
    *Referencias*
    - [[https://gfycat.com/upload][Sitio para subir animaciones - Gfycat.com]]
    - [[http://zenon.en-getafe.org/2007/11/27/xdialog-ventanas-en-scripts][Xdialog ventanas en scripts - Blog Zenon]]
    - [[https://www.it-swarm.dev/es/linux/como-solicito-la-entrada-sinocancelar-en-un-script-de-shell-de-linux/958436319/][Como usar xdialog - it-swarm.dev]]
    - [[https://aur.archlinux.org/packages/xrectsel/][Package xrectsel - AUR Arch Linux]]
    - [[https://wiki.ubuntu.com/CreatingScreencasts][CreatingScreenScasts - Wiki Ubuntu]]
    - [[https://www.archlinuxuser.com/2013/01/how-to-record-desktop-into-gif-using.html][How to record desktop into GIF using byzanz - ArchLinuxUser.com]]

*** Calculadora con notación polaca inversa (rpn - reverse polish notation)

**** Conceptos
     + El comando para ejecutar es *dc* es nativo de linux
     + El orden de la pila se puede interpretar de derecha a izquierda,
       siendo el la derecha un valor que fue ingresado más reciente que el de la izquierda.
    
     #+NAME: Orden en que ingresan los valores
     #+BEGIN_EXAMPLE
     3 16 11 2
     
     1. el 3 fue el primero en ingresar,
     2. el 16 se ingresó después que el 3,
     3. el 11 luego del 16
     4. y el 2 fue el último valor ingresado
     5. la pila quedaría así

     2
     11
     16
     3
     #+END_EXAMPLE

     #+NAME: Orden en que operan los valores 
     #+BEGIN_EXAMPLE
     3 2 11 2 + * /

     1. Primero opera 11 2 +  el resultado será 13, quedando la pila asi 3 2 13 * /
     2. Segundo opera 2 13 * que resulta en 26, quedando la pila asi 3 26 /
     3. Por ultimo opera  3 26 / que resulta en 0,11 aprox.
     4. En la pila solo queda el resultado 0,11 no quedan mas valores por operar
     #+END_EXAMPLE

     | Comando | Descripción                                              |
     | :------ | :------------------------------------------------------- |
     | dc      | Ejecuta la calculadora                                   |
     | p       | muestra el ultimo valor agregado en la pila (en la cima) |
     | f       | lista los valores (en el orden que se agregaron)         |
     | r       | conmuta los ultimos 2 valores (swap)                     |
     | c       | limpia la pila                                           |
     | v       | para obtener la raiz de un valor                         |

     Algunos ejemplos con la notación infija y polaca inversa

     | Notación Infija | Notación Polaca inversa |
     | :-------------  | :---------------------- |
     | (3+5)*10        | 3 5 + 10 *              |
     | A+B*C           | A B C * +               |
     | A*B+C           | A B * C +               |
     | A*B+C*D         | A B * C D * +           |
     | (A+B) / (C-D)   | A B + C D - /           |
     | A*B / C         | A B * C /               |

**** Ejemplos sencillos

     #+NAME: Ejemplo 1, Operaciones sencillas (manera 1)
     #+BEGIN_SRC sh
       dc

       # hagamos 3 11 5 + -
       # si agregamos parentesis para entender el orden de operación
       # quedaría [3 (11 5 +) -]
       #
       # con la notación infija sería 3-(11+5)

       3  # Pila: 3
       11 # Pila: 3 11
       5  # Pila: 3 11 5

       # p, devuelve el último valor ingresado (el que está en la cima de la pila)
       # nuevos valores se apilan arriba, los ingresado al principio quedan debajo (serán los ultimos en operar)
       p  # devuelve 5

       + # 11 5 + es 16
       p # devuelve 16
       # f, devuelve un listado de los valores de la pila
       # estando en la cima el último valor ingresado(más reciente), y debajo los que se agregan al principio
       f # Pila: 3 16

       - # 3 16 - es -13
       p # devuelve -13
       # Pila: -13

       c # c, borra la pila, todos los valores que se hayan ingresado
       # Pila: Vacía, ya no está el -13
     #+END_SRC

     #+NAME: Ejemplo 2, Operaciones sencillas (manera 2)
     #+BEGIN_SRC sh
       dc

       # hagamos 3 11 5 + -
       # si le agregamos parentesis quedaría [3 (11 5 +) -]
       #
       # con notación infija sería 3-(11+5)

       11 # Pila: 11
       5  # Pila: 11 5

       +  # 11 5 + es 16
       p  # devuelve 16
       # Pila: 16

       3 # Pila: 16 3
       r # Pila: 3 16 (conmuta los dos valores más arriba de la pila, los dos más recientes)
       - # 3 16 - es -13
       f # Pila: -13
     #+END_SRC
    
     #+NAME: Ejemplo 3, operaciones normales
     #+BEGIN_SRC sh
       dc

       # hagamos 2 3 11 + 5 - *
       # si agregamos parentesis para entender el orden sería {2 [(3 11 +) 5 -] *}
       #
       # con la notación infija sería: 2*[(3+11) - 5]

       2  # Pila: 2
       3  # Pila: 2 3
       11 # Pila: 2 3 11

       # f, devuelve los valores de la pila,
       # el que estás arriba es el más reciente (será uno de los operandos si ingreso un operador arimético)
       # el que está debajo fue uno de los primeros (será uno de los ultimos valores a operar)
       f  # Pila: 2 3 11

       +  # 3 11 + es 14
       f  # Pila: 2 14

       5  # Pila: 2 14 5
       -  # 14 5 - es 9
       f  # Pila: 2 9
       p  # devuelve 9 (porque es el más reciente, está en la cima de la pila)

       2  # Pila: 2 9
       ,*  # 2 9 * es 18
       f  # devuelve solo 18, porque ya se operaron todos los valores
       p  # también devuelve 18 porque fué el más reciente

       c  # borramos la pila
       f  # Pila: Vacia
       p  # no devolvera valores, no hay

     #+END_SRC

     #+NAME: Ejemplo 4
     #+BEGIN_SRC sh
       dc

       # hagamos 9 5 3 + 2 4 ^ - +
       # si agregaramos parentesis para ver el orden sería {9 [(5 3 +) (2 4 ^) -] +}
       #
       # con la notación infija sería 9+[(5+3)-(2)^4]

       9 # Pila: 9
       5 # Pila: 9 5
       3 # Pila: 9 5 3
       + # 5 3 + que es 8

       f # Pila: 9 8

       2 # Pila: 9 8 2
       4 # Pila: 9 8 2 4
       ^ # 2 ^ 4 es 16

       f # Pila: 9 8 16
       p # devuelve 16 (el resultado más reciente)

       - # 8 16 - es -8
       f # Pila: 9 -8

       + # 9 (-8) - es 1
       f # Pila: 1 (no quedan mas valores por operar, es el único)

       p # devuelve 1 (es el resultado más reciente)
     #+END_SRC


     *Referencias*
     - https://www.computerhope.com/unix/udc.htm
**** Ejemplos de ecuaciones con LaTeX y el comando dc

     \begin{align*}
       \frac{3 + \sqrt{4- \frac{2}{3} }}{(2+7 \times \sqrt{3} )^2} = 0.3
     \end{align*}


     #+NAME: Ejemplo de la ecuacion
     #+BEGIN_SRC sh
       dc
       3   # Pila: 3
       4   # Pila: 3 4
       2   # Pila: 3 4 2
       3 \ # 2 3 / es 0.66
           # Pila: 3 4 0.66
       -   # 4 0.66 - resulta en 3.34
           # Pila: 3 3.34
       +   # 3 3.34 +
           # Pila: 6.34

       2   # Pila: 6.34 2
       7   # Pila: 6.34 2 7
       3   # Pila: 6.34 2 7 3
       v   # 3 raiz, resulta en 1.73
           # Pila: 6.34 2 7 1.73
       ,*   # 7 1.73 * resulta en 12.11
           # Pila: 6.34 2 12.11
       ,*   # 2 12.11 + resulta en 14.11
           # Pila: 6.34 14.11
       2   # Pila: 6.34 14.11 2
       ^   # 14.11 2 ^ resulta en 199.09
           # Pila: 6.34 199.09
       /   # 6.34 199.09 / resulta en 0.03
           # Pila: 0.03

       p   # 0.03 es el unico valor de la pila, no quedan mas valores por operar
       c   # limpiamos la pila
       p   # no hay valores en la pila
     #+END_SRC
*** Calculadora
    - En manjaro probé bc y qalac.
    - Otra manera es usando el comando *expr* pero hay que separar los operandos de los operadores
    *NOTA:* Me pareció que la mejor fué qalac
    
    *Referencias*
    - https://ubunlog.com/calculadora-en-la-terminal-ubuntu/
** TODO [#A] Errores de Manjaro
*** Problemas al instalar paquetes
**** Comandos

     #+NAME: Instalando depurador ddd
     #+BEGIN_SRC shell
       # descargamos un depurador con interfaz gráfica
       git clone https://aur.archlinux.org/ddd.git
       # ingresamos a la carpeta del programa
       cd ddd
       # compilamos el archivo
       makepkg -sci
     #+END_SRC

     #+NAME: Error a solucionar
     #+BEGIN_COMMENT
     ==> Verificando las firmas de las fuentes con gpg...
     ddd-3.3.12.tar.gz ... HA FALLADO (clave pública desconocida 6656C593E5158D1A)
     ==> ERROR: ¡No se ha podido verificar alguna de las firmas PGP!
     #+END_COMMENT

     #+NAME: Soluciones para error de clave pgp
     #+BEGIN_SRC shell
       # si el error menciona la clave 0FC3042E345AD05D
       # entonces
       gpg --recv-keys 0FC3042E345AD05D

       # si lo anterior no lo resuelve..
       pacman -Sy archlinux-keyring manjaro-keyring

       sudo pacman-key --populate archlinux manjaro
       sudo pacman-key --refresh-keys

       # si nada lo resuelve, entonces..
       # "no es lo más recomendable"
       makepkg -sic -skippgpcheck
     #+END_SRC

**** Referencias
     + [[http://pgp.key-server.io/][PGP Public Key Server]]
     + [[https://www.genbeta.com/desarrollo/manual-de-gpg-cifra-y-envia-datos-de-forma-segura][Manual de GPG, cifra, firma y envía datos de forma segura - genbeta.com]]
     + [[https://medium.com/@btc_lovera/gu%C3%ADa-openpgp-pgp-y-gpg-lin-53766809f6d1][Guia OpenPGP, PGP, GPG - medium.com]]
     + [[https://ssd.eff.org/es/module/como-usar-pgp-para-linux][Como usar pgp para linux - Surveillance Self-Defense]]
     + https://forum.manjaro.org/t/solved-error-one-or-more-pgp-signatures-could-not-be-verified/50093
     + https://forum.manjaro.org/t/invalid-or-corrupted-package-pgp-signature-different-error-appeared/114966/7
     + https://forum.manjaro.org/t/error-failed-to-commit-transaction-invalid-or-corrupted-package-pgp-signature-errors-occurred-no-packages-were-upgraded/112792/3
     + https://forum.manjaro.org/t/aur-package-fails-to-verify-pgp-gpg-key-unknown-public-key-one-or-more-pgp-signatures-could-not-be-verified/42687
     + https://bbs.archlinux.org/viewtopic.php?id=233480
*** Pasos a organizar
 Mezclar con la parte de particionamiento
 manjaro error: you need to load the kernel first

   #+BEGIN_SRC bash
     cat /etc/lsb-release # para saber la version de manjaro

     sudo fdisk -l
     sudo parted -l

     # Before doing that check in chroot status of kernels:
     mhwd-kernel -l

     # Depending on result I would recommend to install some kernels in addition, e.g. 5.4:
     sudo mhwd-kernel -i linux54
     sudo blkid # in UEFI

     mhwd-kernel -l # gives a list of available kernels
     mhwd-kernel -li # gives a list of installed kernels

     efibootmgr -v
   #+END_SRC
  
 para saber las particiones
 I went to BIOS for another look at what you mention:Secure Boot: disabled.Fast Boot: I see no such option in my BIOS.UEFI: Yes: “Boot Mode” is set to “UEFI”.Selected grub2 bootloader: I’m not quite sure what you mean by this. Is there a place I can go to select it?

 - https://instintobinario.com/rescatar-el-arranque-de-linux-con-la-consola-de-grub2/

 - https://forum.manjaro.org/t/howto-rescue-your-system-error-hook-invalid-value-path/123226
 - https://forum.manjaro.org/t/you-need-to-load-kernel-first-after-failed-update/132141/3
 - https://forum.manjaro.org/t/using-livecd-v17-0-1-and-above-as-grub-to-boot-os-with-broken-bootloader/24916
 - https://classicforum.manjaro.org/index.php?topic=1011.0 
 - https://wiki.manjaro.org/index.php/Restore_the_GRUB_Bootloader
 - https://wiki.manjaro.org/index.php?title=UEFI_-_Install_Guide
 - https://forum.manjaro.org/t/grub-install-error-cannot-find-efi-directory/83380
 - https://forum.manjaro.org/t/node-error-while-loading-shared-libraries-libicui18n-so-60-cannot-open-shared-object-file-no-such-file-or-directory/37553/4
 - https://forum.manjaro.org/t/file-boot-vmlinuz-not-found-after-update-i-did-update-grub-black-screen/121445/2
 - https://forum.manjaro.org/t/howto-rescue-your-system-error-hook-invalid-value-path/123226
 - https://bbs.archlinux.org/viewtopic.php?id=235203
 - https://forum.manjaro.org/t/power-went-out-during-upgrade-file-boot-vmlinuz-5-1-x86-64-not-found/115909/21
 - https://forum.manjaro.org/t/boot-vmlinuz-not-found-after-hibernation/111409/7
 - https://forum.manjaro.org/t/manjaro-error-file-boot-vmlinuz-5-5-x86-64-not-found-after-update/131538/5
 - https://forum.manjaro.org/t/error-file-vmlinuz-5-4-x86-64-not-found/131502/4
 - https://forum.manjaro.org/t/error-file-vmlinuz-5-4-x86-64-not-found/131502/6

 - https://deblinux.wordpress.com/2012/09/22/como-crear-un-live-usb-de-manjaro-linux-y-no-morir-en-el-intento/
 - https://wiki.manjaro.org/index.php?title=Burn_an_ISO_File#Writing_to_a_USB_Stick_in_Linux
 - https://www.linuxadictos.com/17781.html
 - https://archlinuxlatinoamerica.wordpress.com/2016/10/08/crear-pendriveusb-booteable-desde-nuestra-terminal-en-gnulinux/
 - https://wiki.manjaro.org/index.php?title=Burn_an_ISO_File

  
 The issue is usually provoked when you don't maintain your system at regular intervals - and I am not thinking yearly - because such neglect will often result in similar problems.As the issue stems from a change in pacman code - you may be affected if you install from an ISO previous to 18.1.5.More technical it is a change to pacman and libalpm from 5.1 to 5.2. Users keeping their system up-to-date are not affected - users neglecting updates or installing from an older ISO are affected.1ra Solucion
 You need an ISO. Boot your system using the ISO and chroot into the installation.# manjaro-chroot -a
 Update pacmanFirst step is to update pacman - this may succeed or it may not# pacman -S pacman

 Otraou might also suffer from a faulty kernel-initramfs image. So enter your installation with chroot and update your packages.
 sudo pacman -SyuThen recreate the kernel
 sudo mkinitcpio -p linux
 And then redo the grub.cfg
 sudo update-grub2da SolucionOnce you booted in Live media and you chroot the installed system, then you run:manjaro-chroot -asudo pacman -Syyu - to complete the update
 sudo pacman -S grub
 sudo grub-install /dev/sda - for this you have to make sure the installed system is on sda
 sudo update-grub
 then reboot into your system, after you removed the live media install USB.
 ARREGLAR GRUBhttps://wiki.manjaro.org/index.php/Restore_the_GRUB_Bootloader2.) Create the /boot/efi directorysudo mkdir /boot/efi
 3.) Mount the EFI partition as /boot/efisudo mount /dev/sdXY /boot/efiX = Alphabet of the drive = a,b,c ...Y = Partition number of the EFI partition = 1,2,3,4...Example - /dev/sda4
 4.) Re-install Grub.sudo grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=manjaro --recheck
 5.) Update Grub configuration file.sudo update-grub
** TODO [#A] Guia Linux Que hacer luego de Instalar Linux
*** 1. Comandos Utiles
|------------+--------------------------|
| Comando    | Descripcion              |
|------------+--------------------------|
| pacman -Ss | para buscar un paquete   |
| pacman -S  | para instalar un paquete |
|------------+--------------------------|
*** 2. Instalamos Paquetes 
     #+BEGIN_SRC sh
  # Navegador web minimalista que utiliza comandos de vim
  sudo pacman -S qutebrowser
  # Gestor de directorios por comandos
  sudo pacman -S ranger
  # Nuevo gestor de paquetes# aurman ?

  # otros
  sudo pacman -S telegram-desktop
    #+END_SRC
*** 3. Configuramos Github
    + Para evitar escribir usuario y clave en cada push trabajos con la clave publica y privada.
    + Abrimos la terminal e ingresamos los siguientes comandos.

    #+BEGIN_SRC sh
      # generamos la clave publica y privada
      ssh-keygen
      # buscamos el archivo que tiene la clave publica y lo mostramos por pantalla
      find ~ -name "id_rsa.pub" | xargs cat
      # buscamos el archivo de la clave pública que generamos# la copiamos y lo 
      # agregamos en la configuración de git# https://github.com/settings/keys
      # agregamos git a la lista de host confiables
      ssh -T git@github.com
    #+END_SRC

*** 4. Instalar y Configurar Emacs
**** 4.1 Instalar y Configurar

     #+BEGIN_SRC sh
       # instalamos emacs
       sudo pacman -S emacs
       # clonamos la configuracion de spacemacs en emacs
       git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
       # cambiamos la rama por develop, tiene mas funcionalidades (ej. treemacs)
       cd ~/.emacs.d && git checkout develop
     #+END_SRC
**** 4.2  Activar el modo hibrido
     + Modificar en el archivo de configuracion de spacemacs en `~/.spacemacs““;; encontrar la siguiente linea, debe quedar de esta manera con hybrid

     #+BEGIN_SRC sh
       dotspacemacs-editing-style 'hybrid`
     #+END_SRC
**** 4.3 Activamos layers
     
     + Activar algunos layers utilesBuscar la linea `dotspacemacs-configuration-layers` del archivo `~/.spacemacs` y agregar o descomentar las siguientes lineas“`

     #+BEGIN_SRC sh
       ;; para control de versiones deproyectos
          git
       ;; para usar el org-mode y organizar archivos con tareas
          org
     #+END_SRC
     
     **Referencias**
     + https://github.com/Alexander-Miller/treemacs/blob/master/README.org
*** [TODO] Versionar Dotfiles (PENDIENTE)
    
** Guia del Gestor de Archivos Ranger
*** Filtrar archivos

    1. Presionar zf seguido de la expresion regular
    2. Presionar v para seleccionar los archivos y luego accion que quieras (copiar, cortar)
    3. Presionar nuevamente zf para volver a ver todos los archivos

    *Referencias*
    + https://unix.stackexchange.com/questions/568899/search-and-select-all-matching-files-in-ranger
*** Atajos

    Ranger, tiene los mismos atajos que vim

    + h,l para moverse entre los niveles de los directorios
    + dd para cortar
    + y para copiar
    + p para pegar 

    |------------------------+--------------------------------------------------------------------|
    | Comando                | Descripcion                                                        |
    |------------------------+--------------------------------------------------------------------|
    | :mkdir unDirectorio    | Crear un directorio                                                |
    | :rename otroNombre.txt | Para crear archivos                                                |
    | :touch nuevoFile.txt   | Para modificar el nombre del archivo seleccionado                  |
    | :shell algunComando    | Para ejecutar comandos de terminal en la ruta donde nos situamos   |
    | :set show_hidden!      | Mostrar los archivos ocultos (es necesario el signo de admiración) |
    |------------------------+--------------------------------------------------------------------|

    *Referencias*
    + https://www.atareao.es/software/utilidades/administrador-de-archivos-para-el-terminal/
    + https://openwebinars.net/blog/vim-manual-de-uso-basico/
    + https://unix.stackexchange.com/questions/384325/how-to-create-a-new-file-directory-using-ranger
    + https://linuxconfig.org/manage-your-files-from-the-command-line-with-ranger

** Guia Linux Personalizar
*** Cambiar el cursor y el theme
    - [[https://gitlab.com/cscs/matcha-hacked-cursor][Matcha cursor hacked]]
    - [[https://www.gnome-look.org/p/1188098/][Kolomonggo hacking theme]]
    - https://classicforum.manjaro.org/index.php?topic=29114.0
    - https://forum.manjaro.org/t/i-need-a-good-looking-red-theme-for-plasma/44944
    - https://www.fossmint.com/best-ubuntu-themes/

*** Ocultar el Hostname del prompt
    https://charles4code.blogspot.com/2018/07/show-username-only-without-hostname-in.html
*** Guia de Linux - Particionamiento
   Pendiente en revisar
   - [[https://unix.stackexchange.com/questions/466625/cp-cannot-create-regular-file-permission-denied][Referencia #1]]
   - [[https://www.linuxadictos.com/solucion-al-error-read-only-file-system.html][Referencia #2]]

*** Sincronizar Archivos en Google Drive
    - https://www.youtube.com/watch?v=vPs9K_VC-lg
    - https://www.youtube.com/watch?v=HblhrGIotFo
    - https://rclone.org/drive/
    - https://snapcraft.io/install/rclone/manjaro
    - https://rclone.org/commands/
    - https://snapcraft.io/install/rclone/arch
    - https://www.youtube.com/watch?v=ARGU4HFUxq8
    - https://www.youtube.com/watch?v=G8YMspboIXs
*** Nuevos comandos
    - Crear directorios con subdirectorios, usando el parametro -p en mkdir
      mkdir -p

      Referencias:
      - https://techlandia.com/crear-nuevo-directorio-linux-como_44793/
    - Conocer la particion de un archivo
      Con el comando df

      Referencias
      - https://elbauldelprogramador.com/como-saber-que-particion-pertenece-un/
      - https://www.profesionalreview.com/2018/03/04/saber-particion-esta-instalado-ubuntu/
*** Herramientas de Seguridad
    - Averiguar si el Bitwarden del escritorio funciona en las demas distribuciones ok
    - Comentar lo de la encriptacion de contenido con rclone

** Comando Sed (Manipular Texto)
  Al parecer es bastante parecido al reemplazar de vim

  Referencias:
  - http://www.sromero.org/wiki/linux/aplicaciones/uso_de_sed
  - https://likegeeks.com/es/sed-de-linux/
  - https://www.tecmint.com/linux-sed-command-tips-tricks/
  - https://www.linuxadictos.com/sed-ejemplos-del-comando-magico-para-gnu-linux.html
  - https://blog.desdelinux.net/sed-shell-scripting-comando/

** Pendiente
   - # averiguar por: doas, cmus, qutebrowser, emerge
